version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: restaurant-db
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: restaurant_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - restaurant-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  restaurant-network:
    driver: bridge